apiVersion: apps/v1
kind: Deployment
metadata: 
  name: webapp
spec:
  selector:
    matchLabels:
      app: web-app
  replicas: 3
  template:
    metadata:
      labels:
        app: web-app
        release: "0-5"
    spec:
      containers:
      - name: webapp
        image: richardchesterwood/k8s-fleetman-webapp-angular:release0

 
--- 

apiVersion: v1
kind: Pod
metadata:
  name: queue-app
  labels:
    app: queue-app
    release: "1"
spec:
  containers:
  - name: queue
    image: richardchesterwood/k8s-fleetman-queue:release1