apiVersion: v1
kind: Service
metadata:
  name: fleetman-webapp

spec:
  selector:
    app: "web-app"
  ports:
    - name: http
      port: 80
      nodePort: 30080

  type: NodePort

---

apiVersion: v1
kind: Service
metadata:
  name: fleetman-queue

spec:
  selector:
    app: "queue-app"
    release : "1"

  ports:
    - name: http
      port: 8161
      nodePort: 30010

  type: NodePort